version: "3"
services:
  service:
    image: demo
    container_name: demo
    build: .
    ports:
      - "8081:8081"
    volumes:
      - /usr/local/photo:/usr/photo
    depends_on:
      - mysql
  mysql:
    privileged: true
    image: mysql:8
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: dmy2002916
      MYSQL_DATABASE: webwork
      MYSQL_USER: user
      MYSQL_PASS: dmy2002916
    volumes:
      - ./mysql/log:/var/log/mysql # 映射日志目录，宿主机:容器
      - ./mysql/data:/var/lib/mysql # 映射数据目录，宿主机:容器
      - ./mysql/conf.d:/etc/mysql/conf.d # 映射配置目录，宿主机:容器
      - ./init:/docker-entrypoint-initdb.d/

